### ISSUE TITLE
Export coordinate space

### ISSUE THREAD

**Issue by mjy** [bioip/vronto#23]
* Should have CSV format - URI, label, X, Y, Z, placed
* `Placed` - boolean that says "in model bounds, or not"

* Should have RDF format - these are label for terms (look at OWL format for term annotations)
* Should be 4 labels, corresponding to X, Y, Z, placed
* Should be importable to an ontology using Protégé

**Comment by jamesyang1025** [comment]
Added Scripts to export coordinates to CSV file.

See saved_data.csv in _Unity/Assets/data_ folder
![saved_data](https://user-images.githubusercontent.com/36896710/48586470-a9e83880-e8f5-11e8-9408-67a18b030099.PNG)
