### ISSUE TITLE
identify VR platform to code in

### ISSUE THREAD

**Issue by mjy** [bioip/vronto#3]
* @Moogen and @jamesyang1025 both have experience in Unity, which is the likely target, let's list the other options, with the following considerstations in mind:

* Ease of sharing source code
* Ease of documenting what was done, code and otherwise
* Ease of executing and entering the VR space 
* Ease of interacting with other languages and frameworks (e.g. OWL API)
* Degree of stability and long-term support for the framework/tools

**Comment by jamesyang1025** [comment]
Here are a few guides I found on version control on Github with Unity.
http://www.studica.com/blog/how-to-setup-github-with-unity-step-by-step-instructions
https://www.youtube.com/watch?v=qpXxcvS-g3g
