### ISSUE TITLE
As a User I want to show/hide named sets of points

### ISSUE THREAD

**Issue by mjy** [bioip/vronto#37]
* User part_of
* Use is_a
* Use custom set (e.g. from YAML/JSON config)

**Comment by mjy** [comment]
* Add a config file relationships/object_properties

|uri|object_property|uri|
|---|---|---|
|HAO:123|part_of|HAO:456|

* Add a config file YAML/json "sets"
```json
{
  "main": 
       "HAO:123"
       "HAO:456"
       "HAO:789"
}
```

**Comment by jamesyang1025** [comment]
Added a UI button to show/hide set of points. When showing the set, the page will only display the set of points, disabling points not in this set. When hiding the set, the page will display the original points
